# Netlify deployment configuration
[build]
  command = "chmod +x ./build.sh && ./build.sh && cd client && npm run build"
  publish = "client/dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_USE_PRODUCTION = "false"

# Headers for WASM support
[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Embedder-Policy = "require-corp"
    
# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200