# Render deployment configuration
services:
  - type: web
    name: rust-wasm-react-app
    env: static
    buildCommand: chmod +x ./build.sh && ./build.sh && cd client && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*.wasm
        name: Content-Type
        value: application/wasm
      - path: /*
        name: Cross-Origin-Embedder-Policy  
        value: require-corp